"""Analytics layer: SQL views (``db/views.sql``) + the query service used by the API."""

from app.analytics.service import (
    availability_summary,
    brand_leaderboard,
    catalog_reconciliation,
    category_breakdown,
    category_changes,
    category_drift_report,
    category_tree,
    compliance_report,
    daily_trend,
    http_log,
    kpi_summary,
    list_views,
    new_products,
    pipeline_runs,
    price_change_report,
    price_change_timeline,
    price_history,
    product_detail,
    query_explain,
    removed_products,
    run_detail,
    source_health,
    table_counts,
    top_movers,
)

__all__ = [
    "table_counts",
    "kpi_summary",
    "daily_trend",
    "price_change_timeline",
    "top_movers",
    "category_breakdown",
    "brand_leaderboard",
    "source_health",
    "availability_summary",
    "category_tree",
    "new_products",
    "removed_products",
    "category_changes",
    "catalog_reconciliation",
    "price_history",
    "product_detail",
    "pipeline_runs",
    "run_detail",
    "price_change_report",
    "category_drift_report",
    "compliance_report",
    "http_log",
    "query_explain",
    "list_views",
]
