"""Concrete ingestion sources (free, public, automation-permitted endpoints).

Importing this package registers every source with the global registry.
"""

from __future__ import annotations

from app.ingestion.sources import (  # noqa: F401
    bitstamp,
    books_to_scrape,
    cheapshark,
    cocktaildb,
    coincap,
    coingecko,
    dummyjson,
    fakestore,
    freeapi,
    google_books,
    gutendex,
    itunes,
    itunes_ebooks,
    kraken,
    local_fixture,
    makeup,
    mealdb,
    mmobomb,
    openfoodfacts_prices,
    openlibrary,
    platzi,
    pokemontcg,
    predic8,
    restful_objects,
    sampleapis_coffee,
    sampleapis_switch,
    scrapeme,
    scryfall,
    steam_store,
    stooq,
    ygoprodeck,
)

__all__ = [
    "bitstamp",
    "books_to_scrape",
    "cheapshark",
    "cocktaildb",
    "coincap",
    "coingecko",
    "dummyjson",
    "fakestore",
    "freeapi",
    "google_books",
    "gutendex",
    "itunes",
    "itunes_ebooks",
    "kraken",
    "local_fixture",
    "makeup",
    "mealdb",
    "mmobomb",
    "openfoodfacts_prices",
    "openlibrary",
    "platzi",
    "pokemontcg",
    "predic8",
    "restful_objects",
    "sampleapis_coffee",
    "sampleapis_switch",
    "scrapeme",
    "scryfall",
    "steam_store",
    "stooq",
    "ygoprodeck",
]
