#!/usr/bin/env python3
"""Extract and validate every Mermaid diagram in the documentation.

GitHub renders Mermaid at render time, which means a syntax error surfaces as a
broken box in the README rather than as a failed build. This script makes that a
build failure instead.

Two modes:

    python3 scripts/diagrams.py extract    # write docs/diagrams/out/*.mmd + index.md
    python3 scripts/diagrams.py validate   # parse-check every diagram (needs mmdc)
    python3 scripts/diagrams.py render     # validate and write SVGs alongside

Validation needs the Mermaid CLI:

    npm install -g @mermaid-js/mermaid-cli

Exit code is 0 only when every diagram parses.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "diagrams" / "out"

#: Documents scanned for diagrams, in reading order.
SOURCES = [ROOT / "README.md", *sorted((ROOT / "docs").glob("*.md"))]

BLOCK = re.compile(r"^```mermaid\s*$(.*?)^```\s*$", re.M | re.S)

PUPPETEER_ARGS = (
    "--no-sandbox",
    "--disable-setuid-sandbox",
    "--disable-dev-shm-usage",
    "--disable-gpu",
)


@dataclass
class Diagram:
    """One Mermaid block, and where it came from."""

    source: Path
    position: int
    kind: str
    body: str

    @property
    def label(self) -> str:
        return f"{self.source.relative_to(ROOT)} (diagram {self.position}, {self.kind})"

    @property
    def slug(self) -> str:
        stem = self.source.relative_to(ROOT).with_suffix("").as_posix()
        return re.sub(r"[^a-zA-Z0-9_-]", "_", stem.replace("/", "-"))


def collect() -> list[Diagram]:
    """Every Mermaid block across every documentation file."""
    found: list[Diagram] = []
    for source in SOURCES:
        if not source.is_file():
            continue
        text = source.read_text(encoding="utf-8")
        for position, body in enumerate(BLOCK.findall(text), start=1):
            first = body.strip().split("\n", 1)[0]
            found.append(
                Diagram(
                    source=source,
                    position=position,
                    kind=first[:60] or "(empty)",
                    body=body if body.endswith("\n") else body + "\n",
                )
            )
    return found


def extract(diagrams: list[Diagram]) -> list[Path]:
    """Write each block to docs/diagrams/out and build a Markdown index."""
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)

    written: list[Path] = []
    index = [
        "# Extracted Mermaid diagrams",
        "",
        "Generated by `python3 scripts/diagrams.py extract`. "
        "GitHub renders the diagrams inline; these files exist for offline "
        "rendering, export and review.",
        "",
        "| Source | Diagram type | File |",
        "| --- | --- | --- |",
    ]

    for number, diagram in enumerate(diagrams, start=1):
        target = OUT / f"{diagram.slug}_{number:02d}.mmd"
        target.write_text(diagram.body, encoding="utf-8")
        written.append(target)
        index.append(f"| {diagram.label} | `{target.name}` |")

    (OUT / "index.md").write_text("\n".join(index) + "\n", encoding="utf-8")
    return written


def _mmdc_available() -> bool:
    return shutil.which("mmdc") is not None


def validate(diagrams: list[Diagram], *, render: bool = False) -> int:
    """Parse-check every diagram. Returns a process exit code."""
    if not _mmdc_available():
        print(
            "error: mmdc not found.\n\n"
            "  Install the Mermaid CLI:\n\n"
            "      npm install -g @mermaid-js/mermaid-cli\n\n"
            "  CI runs this check as part of the docs job.",
            file=sys.stderr,
        )
        return 127

    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        config = tmp_path / "puppeteer.json"
        config.write_text(
            '{"args": [' + ", ".join(f'"{a}"' for a in PUPPETEER_ARGS) + "]}",
            encoding="utf-8",
        )

        ok = 0
        failed: list[tuple[str, str]] = []

        for number, diagram in enumerate(diagrams, start=1):
            source_file = tmp_path / f"{number:03d}.mmd"
            source_file.write_text(diagram.body, encoding="utf-8")
            target = (
                OUT / f"{diagram.slug}_{number:02d}.svg" if render else tmp_path / f"{number:03d}.svg"
            )

            result = subprocess.run(
                ["mmdc", "-i", str(source_file), "-o", str(target), "-p", str(config), "-q"],
                capture_output=True,
                text=True,
                timeout=120,
                stdin=subprocess.DEVNULL,
            )

            if result.returncode == 0:
                ok += 1
                print(f"  \033[32mok\033[0m   {diagram.label}")
            else:
                detail = (result.stderr or result.stdout or "").strip().splitlines()
                message = "\n         ".join(detail[:5]) or "(no output)"
                failed.append((diagram.label, message))
                print(f"  \033[31mFAIL\033[0m {diagram.label}\n         {message}")

    total = len(diagrams)
    print("\n" + "─" * 46)
    if not failed:
        print(f"\033[32mAll {total} diagrams parsed successfully.\033[0m")
        if render:
            print(f"SVGs written to {OUT.relative_to(ROOT)}/")
        return 0

    print(f"\033[31m{len(failed)} of {total} diagrams failed to parse.\033[0m")
    for label, _ in failed:
        print(f"  - {label}")
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument(
        "command",
        choices=("extract", "validate", "render"),
        help="extract .mmd files, parse-check them, or render SVGs",
    )
    args = parser.parse_args()

    diagrams = collect()
    if not diagrams:
        print("No Mermaid diagrams found.", file=sys.stderr)
        return 1

    print(f"Found {len(diagrams)} diagrams across {len({d.source for d in diagrams})} files.")

    if args.command == "extract":
        written = extract(diagrams)
        print(f"Extracted {len(written)} files to {OUT.relative_to(ROOT)}/")
        print(f"Index written to {(OUT / 'index.md').relative_to(ROOT)}")
        return 0

    if args.command == "render":
        extract(diagrams)
        return validate(diagrams, render=True)

    return validate(diagrams)


if __name__ == "__main__":
    raise SystemExit(main())