"""What belongs to the warehouse schema, and what does not.

Alembic autogenerates by diffing the ORM metadata against what it finds in the
database, so any table present in the database but absent from the models is proposed
as a DROP. That is correct in isolation and dangerous in a shared server: anything else
living in the same database would be deleted by the next autogenerated revision.

The rules live here rather than inside `migrations/env.py` so they can be tested
without an Alembic runtime context, which is what a plain `import` of that module
requires.
"""

from __future__ import annotations

from typing import Any

#: Prefixes that belong to something other than the warehouse schema.
#:
#: ``vw_*``       analytical views, created from ``db/views.sql`` by
#:                ``apply_views()``, not by the ORM. Autogenerate would DROP all
#:                twenty of them on every run.
#: ``alembic_*``  Alembic's own bookkeeping.
#: the rest       Airflow's ~40 orchestration tables. Airflow now has its own
#:                metadata database, but an existing deployment may still carry
#:                them, and dropping them would destroy the DAG history.
FOREIGN_PREFIXES: tuple[str, ...] = (
    "vw_",
    "alembic_",
    # Airflow metadata
    "ab_",
    "dag",
    "dagrun_",
    "task_",
    "trigger",
    "xcom",
    "slot_",
    "sla_",
    "import_error",
    "job",
    "log",
    "log_template",
    "variable",
    "connection",
    "session",
    "rendered_",
    "serialized_dag",
    "callback_request",
    "dataset",
)

#: Names matched exactly, for the Airflow tables that are single words.
FOREIGN_NAMES: frozenset[str] = frozenset(
    {
        "ab_permission",
        "ab_role",
        "ab_user",
        "ab_view_menu",
        "job",
        "log",
        "variable",
        "connection",
        "session",
        "trigger",
        "import_error",
    }
)


def is_warehouse_table(name: str) -> bool:
    """True when Alembic should consider `name` part of the warehouse schema."""
    if not name:
        return False
    if name in FOREIGN_NAMES:
        return False
    return not name.startswith(FOREIGN_PREFIXES)


def include_object(
    obj: Any,  # noqa: ANN401 - Alembic passes dialect-specific objects here
    name: str,
    type_: str,
    reflected: bool,
    compare_to: Any,  # noqa: ANN401
) -> bool:
    """The `include_object` hook Alembic calls for every candidate object."""
    if type_ != "table":
        # Indexes, columns and constraints are only ever considered alongside a
        # table that survived the filter, so they pass through.
        return True
    return is_warehouse_table(name)


__all__ = ["FOREIGN_NAMES", "FOREIGN_PREFIXES", "include_object", "is_warehouse_table"]
